package Vue;

import java.awt.event.ActionListener;
import java.util.ArrayList;

/**
 * Classe décrivant l'interface graphique de l'application. Les boutons de
 * traitements sont affichés en fonction du nombre de .class présent dans le
 * répertoire. Par convention, on choisit qu'on ne peux pas charger plus de
 * trois traitements
 * 
 * @author GR03
 */
public class Screen extends javax.swing.JFrame {

	/**
	 * Creates new form Screen
	 */
	public Screen(ArrayList<String> s) {
		initComponents(s);
	}

	/**
	 * contrôle l'affichage des boutons de traitements
	 * 
	 * @param n
	 */
	public void setNbCommande(int n) {
		switch (n) {
		case 0:
			jButton1.setVisible(false);
			jTextField1.setVisible(false);
			jButton2.setVisible(false);
			jTextField2.setVisible(false);
			jButton3.setVisible(false);
			jTextField3.setVisible(false);
			break;
		case 1:
			jButton2.setVisible(false);
			jTextField2.setVisible(false);
			jButton3.setVisible(false);
			jTextField3.setVisible(false);
			break;
		case 2:
			jButton3.setVisible(false);
			jTextField3.setVisible(false);
			break;
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents(ArrayList<String> s) {

		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jTextField1 = new javax.swing.JTextField();
		jTextField2 = new javax.swing.JTextField();
		jTextField3 = new javax.swing.JTextField();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		setNbCommande(s.size());
		switch (s.size()) {
		case 1:
			jButton1.setText(s.get(0));
			break;
		case 2:
			jButton1.setText(s.get(0));
			jButton2.setText(s.get(1));
			break;
		case 3:
			jButton1.setText(s.get(0));
			jButton2.setText(s.get(1));
			jButton3.setText(s.get(2));
			break;
		}

		jButton4.setText("File");

		jTextField1.setText("Result1");

		jTextField2.setText("Result2");

		jTextField3.setText("Result3");

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane1.setViewportView(jTextArea1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										285,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(45, 45, 45)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING,
												false)
												.addComponent(
														jButton2,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(
														jButton3,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(
														jButton1,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										17, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														jTextField3,
														javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														72,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
																.addComponent(
																		jTextField2,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		72,
																		Short.MAX_VALUE)
																.addComponent(
																		jTextField1)))
								.addContainerGap())
				.addGroup(
						layout.createSequentialGroup()
								.addGap(119, 119, 119)
								.addComponent(jButton4)
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(33,
																		92,
																		Short.MAX_VALUE)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jButton1)
																				.addComponent(
																						jTextField1,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(40, 40,
																		40)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jButton2)
																				.addComponent(
																						jTextField2,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(37, 37,
																		37)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jButton3)
																				.addComponent(
																						jTextField3,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addComponent(
																		jScrollPane1)))
								.addGap(18, 18, 18).addComponent(jButton4)
								.addGap(21, 21, 21)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Screen.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Screen.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Screen.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Screen.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;

	// End of variables declaration//GEN-END:variables

	public void addTraitement1Listener(ActionListener al) {
		jButton1.addActionListener(al);
	}

	public void addTraitement2Listener(ActionListener al) {
		jButton2.addActionListener(al);
	}

	public void addTraitement3Listener(ActionListener al) {
		jButton3.addActionListener(al);
	}

	public javax.swing.JTextField getTextField1() {
		return jTextField1;
	}

	public javax.swing.JTextField getTextField2() {
		return jTextField2;
	}

	public javax.swing.JTextField getTextField3() {
		return jTextField3;
	}

	public javax.swing.JTextArea getTextArea1() {
		return jTextArea1;
	}

	public javax.swing.JButton getSelectButton() {
		return jButton4;
	}

	public void addSelectListener(ActionListener select) {
		jButton4.addActionListener(select);
	}
}
